/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author jtwes
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Product product;
    public CreateJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductName = new javax.swing.JLabel();
        fieldProductName = new javax.swing.JTextField();
        lblCreateAProduct = new javax.swing.JLabel();
        lblProductDescription = new javax.swing.JLabel();
        fieldProductDescription = new javax.swing.JTextField();
        lblProductAvailable = new javax.swing.JLabel();
        fieldProductNumberAvailable = new javax.swing.JTextField();
        lblProductPrice = new javax.swing.JLabel();
        fieldProductPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldMfrStreetName = new javax.swing.JTextField();
        lblMfrStreetName = new javax.swing.JLabel();
        lblMfrUnitNumber = new javax.swing.JLabel();
        fieldMfrUnitNumber = new javax.swing.JTextField();
        fieldMfrCity = new javax.swing.JTextField();
        lblMfrCity = new javax.swing.JLabel();
        lblMfrZipCode = new javax.swing.JLabel();
        fieldMfrZipCode = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fieldShippingStreetName = new javax.swing.JTextField();
        lblShippingStreetName = new javax.swing.JLabel();
        lblShippingUnitNumber = new javax.swing.JLabel();
        fieldShippingUnitNumber = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipCode = new javax.swing.JLabel();
        fieldShippingZipCode = new javax.swing.JTextField();
        btnProductSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(202, 242, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductName.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductName.setText("Name");
        lblProductName.setToolTipText("");
        add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        fieldProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldProductNameActionPerformed(evt);
            }
        });
        add(fieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 240, -1));

        lblCreateAProduct.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lblCreateAProduct.setText("Create a Product");
        lblCreateAProduct.setToolTipText("");
        add(lblCreateAProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        lblProductDescription.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductDescription.setText("Description");
        lblProductDescription.setToolTipText("");
        add(lblProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));
        add(fieldProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 240, -1));

        lblProductAvailable.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductAvailable.setText("Number Available");
        lblProductAvailable.setToolTipText("");
        add(lblProductAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));
        add(fieldProductNumberAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 60, -1));

        lblProductPrice.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductPrice.setText("Price");
        lblProductPrice.setToolTipText("");
        add(lblProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));
        add(fieldProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 60, -1));

        jLabel6.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Manufacturer Address");
        jLabel6.setToolTipText("");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        add(fieldMfrStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 130, -1));

        lblMfrStreetName.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrStreetName.setText("Street Name*");
        lblMfrStreetName.setToolTipText("");
        add(lblMfrStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblMfrUnitNumber.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrUnitNumber.setText("Unit Number");
        lblMfrUnitNumber.setToolTipText("");
        add(lblMfrUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        add(fieldMfrUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 70, -1));
        add(fieldMfrCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 130, -1));

        lblMfrCity.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrCity.setText("City*");
        lblMfrCity.setToolTipText("");
        add(lblMfrCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        lblMfrZipCode.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrZipCode.setText("Zip Code*");
        lblMfrZipCode.setToolTipText("");
        add(lblMfrZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        add(fieldMfrZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 70, -1));

        jLabel16.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel16.setText("Shipping Address");
        jLabel16.setToolTipText("");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 30));
        add(fieldShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 130, -1));

        lblShippingStreetName.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingStreetName.setText("Street Name*");
        lblShippingStreetName.setToolTipText("");
        add(lblShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 20));

        lblShippingUnitNumber.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingUnitNumber.setText("Unit Number");
        lblShippingUnitNumber.setToolTipText("");
        add(lblShippingUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, 20));
        add(fieldShippingUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 70, -1));
        add(fieldShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 130, -1));

        lblShippingCity.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingCity.setText("City*");
        lblShippingCity.setToolTipText("");
        add(lblShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, 20));

        lblShippingZipCode.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingZipCode.setText("Zip Code*");
        lblShippingZipCode.setToolTipText("");
        add(lblShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, 20));
        add(fieldShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 70, -1));

        btnProductSave.setText("Save");
        btnProductSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductSaveActionPerformed(evt);
            }
        });
        add(btnProductSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductSaveActionPerformed
        //collect all data in fields and place into product object
        
        //product
        String productName = fieldProductName.getText();
        String productDescription = fieldProductDescription.getText();
        String productNumberAvailable = fieldProductNumberAvailable.getText();
        String productPrice = fieldProductPrice.getText();
        //manufacturer address
        String mfrStreet = fieldMfrStreetName.getText();
        String mfrUnit = fieldMfrUnitNumber.getText();
        String mfrCity = fieldMfrCity.getText();
        String mfrZipCode = fieldMfrZipCode.getText();
        //shipping address
        String shipStreet = fieldShippingStreetName.getText();
        String shipUnit = fieldShippingUnitNumber.getText();
        String shipCity = fieldShippingCity.getText();
        String shipZipCode = fieldShippingZipCode.getText();
        
        //verification, name is required, if not entered then we will not save data to the object.
        if(productName.isBlank()){
            JOptionPane.showMessageDialog(this, "A Product Name is Required", "Failed to Save",JOptionPane.INFORMATION_MESSAGE);
        }else{
            
            /// setting all the product data in our object product.
            product.setName(productName);
            product.setDescription(productDescription);
            product.setAvailNum(productNumberAvailable);
            product.setPrice(productPrice);

            // product fields
            product.setName(productName);
            product.setDescription(productDescription);
            product.setAvailNum(productNumberAvailable);
            product.setPrice(productPrice);

            // manufacturer address
            product.getManufactureAddress().setStreetName(mfrStreet);
            product.getManufactureAddress().setUnitNum(mfrUnit);
            product.getManufactureAddress().setCity(mfrCity);
            product.getManufactureAddress().setZipCode(mfrZipCode);

            // shipping address
            product.getShippingAddress().setStreetName(shipStreet);
            product.getShippingAddress().setUnitNum(shipUnit);
            product.getShippingAddress().setCity(shipCity);
            product.getShippingAddress().setZipCode(shipZipCode);
            //pop-up message for success
            JOptionPane.showMessageDialog(this, "Saved Successfull!", "Success",JOptionPane.INFORMATION_MESSAGE);

            //clear text on all fields
            fieldProductName.setText("");
            fieldProductDescription.setText("");
            fieldProductNumberAvailable.setText("");
            fieldProductPrice.setText("");
            //manufacturer address
            fieldMfrStreetName.setText("");
            fieldMfrUnitNumber.setText("");
            fieldMfrCity.setText("");
            fieldMfrZipCode.setText("");
            //shipping address
            fieldShippingStreetName.setText("");
            fieldShippingUnitNumber.setText("");
            fieldShippingCity.setText("");
            fieldShippingZipCode.setText("");
        }
    }//GEN-LAST:event_btnProductSaveActionPerformed

    private void fieldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldProductNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductSave;
    private javax.swing.JTextField fieldMfrCity;
    private javax.swing.JTextField fieldMfrStreetName;
    private javax.swing.JTextField fieldMfrUnitNumber;
    private javax.swing.JTextField fieldMfrZipCode;
    private javax.swing.JTextField fieldProductDescription;
    private javax.swing.JTextField fieldProductName;
    private javax.swing.JTextField fieldProductNumberAvailable;
    private javax.swing.JTextField fieldProductPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreetName;
    private javax.swing.JTextField fieldShippingUnitNumber;
    private javax.swing.JTextField fieldShippingZipCode;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCreateAProduct;
    private javax.swing.JLabel lblMfrCity;
    private javax.swing.JLabel lblMfrStreetName;
    private javax.swing.JLabel lblMfrUnitNumber;
    private javax.swing.JLabel lblMfrZipCode;
    private javax.swing.JLabel lblProductAvailable;
    private javax.swing.JLabel lblProductDescription;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreetName;
    private javax.swing.JLabel lblShippingUnitNumber;
    private javax.swing.JLabel lblShippingZipCode;
    // End of variables declaration//GEN-END:variables
}
