/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Product;

/**
 *
 * @author jtwes
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Product product;
    public ViewJPanel(Product p) {
        initComponents();
        product = p;
        displayProduct();
    }
    
    private void displayProduct(){
        ///Grab all the data from object "product" and display in the views corresponding fields.
        fieldProductName.setText(product.getName());
        fieldProductDescription.setText(product.getDescription());  
        fieldProductNumberAvailable.setText(product.getAvailNum());
        fieldProductPrice.setText(product.getPrice());
                
        fieldMfrCity.setText(product.getManufactureAddress().getCity());
        fieldMfrStreetName.setText(product.getManufactureAddress().getStreetName());
        fieldMfrUnitNumber.setText(product.getManufactureAddress().getUnitNum());
        fieldMfrZipCode.setText(product.getManufactureAddress().getZipCode());
        
        fieldShippingCity.setText(product.getShippingAddress().getCity());
        fieldShippingStreetName.setText(product.getShippingAddress().getStreetName());
        fieldShippingUnitNumber.setText(product.getShippingAddress().getUnitNum());
        fieldShippingZipCode.setText(product.getShippingAddress().getZipCode());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductName = new javax.swing.JLabel();
        fieldProductName = new javax.swing.JTextField();
        lblCreateAProduct = new javax.swing.JLabel();
        lblProductDescription = new javax.swing.JLabel();
        fieldProductDescription = new javax.swing.JTextField();
        lblProductAvailable = new javax.swing.JLabel();
        fieldProductNumberAvailable = new javax.swing.JTextField();
        lblProductPrice = new javax.swing.JLabel();
        fieldProductPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldMfrStreetName = new javax.swing.JTextField();
        lblMfrStreetName = new javax.swing.JLabel();
        lblMfrUnitNumber = new javax.swing.JLabel();
        fieldMfrUnitNumber = new javax.swing.JTextField();
        fieldMfrCity = new javax.swing.JTextField();
        lblMfrCity = new javax.swing.JLabel();
        lblMfrZipCode = new javax.swing.JLabel();
        fieldMfrZipCode = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fieldShippingStreetName = new javax.swing.JTextField();
        lblShippingStreetName = new javax.swing.JLabel();
        lblShippingUnitNumber = new javax.swing.JLabel();
        fieldShippingUnitNumber = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipCode = new javax.swing.JLabel();
        fieldShippingZipCode = new javax.swing.JTextField();

        setBackground(new java.awt.Color(242, 255, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductName.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductName.setText("Name");
        lblProductName.setToolTipText("");
        add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 20));
        add(fieldProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 240, 30));

        lblCreateAProduct.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lblCreateAProduct.setText("Create a Product");
        lblCreateAProduct.setToolTipText("");
        add(lblCreateAProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, 30));

        lblProductDescription.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductDescription.setText("Description");
        lblProductDescription.setToolTipText("");
        add(lblProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 20));
        add(fieldProductDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 240, 30));

        lblProductAvailable.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductAvailable.setText("Number Available");
        lblProductAvailable.setToolTipText("");
        add(lblProductAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, 20));
        add(fieldProductNumberAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 60, 30));

        lblProductPrice.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblProductPrice.setText("Price");
        lblProductPrice.setToolTipText("");
        add(lblProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, 20));
        add(fieldProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 60, 30));

        jLabel6.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Manufacturer Address");
        jLabel6.setToolTipText("");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 30));
        add(fieldMfrStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 130, 30));

        lblMfrStreetName.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrStreetName.setText("Street Name*");
        lblMfrStreetName.setToolTipText("");
        add(lblMfrStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        lblMfrUnitNumber.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrUnitNumber.setText("Unit Number");
        lblMfrUnitNumber.setToolTipText("");
        add(lblMfrUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));
        add(fieldMfrUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, 30));
        add(fieldMfrCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 130, 30));

        lblMfrCity.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrCity.setText("City*");
        lblMfrCity.setToolTipText("");
        add(lblMfrCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 20));

        lblMfrZipCode.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblMfrZipCode.setText("Zip Code*");
        lblMfrZipCode.setToolTipText("");
        add(lblMfrZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, 20));
        add(fieldMfrZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 70, 30));

        jLabel16.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel16.setText("Shipping Address");
        jLabel16.setToolTipText("");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 30));
        add(fieldShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 130, 30));

        lblShippingStreetName.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingStreetName.setText("Street Name*");
        lblShippingStreetName.setToolTipText("");
        add(lblShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 20));

        lblShippingUnitNumber.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingUnitNumber.setText("Unit Number");
        lblShippingUnitNumber.setToolTipText("");
        add(lblShippingUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, 20));
        add(fieldShippingUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, 30));
        add(fieldShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 130, 30));

        lblShippingCity.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingCity.setText("City*");
        lblShippingCity.setToolTipText("");
        add(lblShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, 20));

        lblShippingZipCode.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        lblShippingZipCode.setText("Zip Code*");
        lblShippingZipCode.setToolTipText("");
        add(lblShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, 20));
        add(fieldShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 70, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldMfrCity;
    private javax.swing.JTextField fieldMfrStreetName;
    private javax.swing.JTextField fieldMfrUnitNumber;
    private javax.swing.JTextField fieldMfrZipCode;
    private javax.swing.JTextField fieldProductDescription;
    private javax.swing.JTextField fieldProductName;
    private javax.swing.JTextField fieldProductNumberAvailable;
    private javax.swing.JTextField fieldProductPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreetName;
    private javax.swing.JTextField fieldShippingUnitNumber;
    private javax.swing.JTextField fieldShippingZipCode;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCreateAProduct;
    private javax.swing.JLabel lblMfrCity;
    private javax.swing.JLabel lblMfrStreetName;
    private javax.swing.JLabel lblMfrUnitNumber;
    private javax.swing.JLabel lblMfrZipCode;
    private javax.swing.JLabel lblProductAvailable;
    private javax.swing.JLabel lblProductDescription;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreetName;
    private javax.swing.JLabel lblShippingUnitNumber;
    private javax.swing.JLabel lblShippingZipCode;
    // End of variables declaration//GEN-END:variables
}
